2020-08-05T01:13:34.1592897+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T01:13:34.1788897+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T01:13:34.1790447+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T01:13:46.2767893+05:30 80000022-0003-f200-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T01:13:50.8619343+05:30 80000022-0003-f200-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T01:15:03.7131017+05:30 80000055-0000-fd00-b63f-84710c7967bb [ERR] The view '"SaveAssessment"' was not found. Searched locations: ["/Views/Assessment/SaveAssessment.cshtml", "/Views/Shared/SaveAssessment.cshtml"] (9bb2756c)
2020-08-05T01:15:05.2722971+05:30 80000055-0000-fd00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: The view 'SaveAssessment' was not found. The following locations were searched:
/Views/Assessment/SaveAssessment.cshtml
/Views/Shared/SaveAssessment.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2020-08-05T01:19:59.2912776+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T01:19:59.3444404+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T01:19:59.3449276+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T01:20:08.7452052+05:30 80000059-0000-fd00-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T01:20:11.8156680+05:30 80000059-0000-fd00-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T01:21:19.2708616+05:30 80000043-0002-fb00-b63f-84710c7967bb [ERR] The view '"SaveAssessment"' was not found. Searched locations: ["/Views/Assessment/SaveAssessment.cshtml", "/Views/Shared/SaveAssessment.cshtml"] (9bb2756c)
2020-08-05T01:21:20.3600321+05:30 80000043-0002-fb00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: The view 'SaveAssessment' was not found. The following locations were searched:
/Views/Assessment/SaveAssessment.cshtml
/Views/Shared/SaveAssessment.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2020-08-05T01:22:01.2183934+05:30 80000063-0000-fd00-b63f-84710c7967bb [ERR] The view '"SaveAssessment"' was not found. Searched locations: ["/Views/Assessment/SaveAssessment.cshtml", "/Views/Shared/SaveAssessment.cshtml"] (9bb2756c)
2020-08-05T01:22:01.2502584+05:30 80000063-0000-fd00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: The view 'SaveAssessment' was not found. The following locations were searched:
/Views/Assessment/SaveAssessment.cshtml
/Views/Shared/SaveAssessment.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2020-08-05T01:22:50.6709576+05:30 8000002c-0003-f200-b63f-84710c7967bb [ERR] The view '"SaveAssessment"' was not found. Searched locations: ["/Views/Assessment/SaveAssessment.cshtml", "/Views/Shared/SaveAssessment.cshtml"] (9bb2756c)
2020-08-05T01:22:50.7200982+05:30 8000002c-0003-f200-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: The view 'SaveAssessment' was not found. The following locations were searched:
/Views/Assessment/SaveAssessment.cshtml
/Views/Shared/SaveAssessment.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2020-08-05T01:58:34.7837775+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T01:58:34.8067923+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T01:58:34.8069235+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T01:58:50.4173289+05:30 80000038-0000-fa00-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T01:58:53.4314696+05:30 80000038-0000-fa00-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T02:02:19.1477961+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T02:02:19.2003843+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T02:02:19.2005337+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T02:02:34.7144823+05:30 80000043-0003-f300-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T02:02:37.9680167+05:30 80000043-0003-f300-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T02:03:41.7042221+05:30 8000004b-0002-fb00-b63f-84710c7967bb [ERR] The view '"SaveAssessment"' was not found. Searched locations: ["/Views/Assessment/SaveAssessment.cshtml", "/Views/Shared/SaveAssessment.cshtml"] (9bb2756c)
2020-08-05T02:03:41.8326892+05:30 8000004b-0002-fb00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: The view 'SaveAssessment' was not found. The following locations were searched:
/Views/Assessment/SaveAssessment.cshtml
/Views/Shared/SaveAssessment.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2020-08-05T02:06:12.1153239+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T02:06:12.1423441+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T02:06:12.1427313+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T02:06:23.7781789+05:30 80000053-0002-f700-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T02:06:26.9687415+05:30 80000053-0002-f700-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T02:09:14.5386437+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T02:09:14.5644287+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T02:09:14.5645627+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T02:09:23.1300157+05:30 80000045-0002-f900-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T02:09:26.3983486+05:30 80000045-0002-f900-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T02:15:06.4090977+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T02:15:06.4393650+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T02:15:06.4395428+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T02:15:15.2728629+05:30 8000004d-0003-f800-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T02:15:18.6897944+05:30 8000004d-0003-f800-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T02:18:35.3344121+05:30 80000052-0003-f400-b63f-84710c7967bb [ERR] The view '"SaveAssessment"' was not found. Searched locations: ["/Views/Assessment/SaveAssessment.cshtml", "/Views/Shared/SaveAssessment.cshtml"] (9bb2756c)
2020-08-05T02:18:35.4587441+05:30 80000052-0003-f400-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: The view 'SaveAssessment' was not found. The following locations were searched:
/Views/Assessment/SaveAssessment.cshtml
/Views/Shared/SaveAssessment.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2020-08-05T02:20:57.8032108+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T02:20:57.8299309+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T02:20:57.8300565+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T02:21:06.6138037+05:30 80000049-0003-f300-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T02:21:09.6314801+05:30 80000049-0003-f300-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T02:24:56.7424113+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T02:24:56.7708814+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T02:24:56.7711090+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T02:25:22.1190761+05:30 80000016-0002-f800-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T02:25:25.1983657+05:30 80000016-0002-f800-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T02:33:03.0386270+05:30 8000001e-0002-f800-b63f-84710c7967bb [ERR] The view '"SaveAssessment"' was not found. Searched locations: ["/Views/Assessment/SaveAssessment.cshtml", "/Views/Shared/SaveAssessment.cshtml"] (9bb2756c)
2020-08-05T02:33:03.1762904+05:30 8000001e-0002-f800-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: The view 'SaveAssessment' was not found. The following locations were searched:
/Views/Assessment/SaveAssessment.cshtml
/Views/Shared/SaveAssessment.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2020-08-05T02:38:14.6852545+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T02:38:14.7073871+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T02:38:14.7075439+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T02:38:23.4257249+05:30 80000031-0003-f500-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T02:38:26.9453560+05:30 80000031-0003-f500-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T02:42:27.9402899+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T02:42:27.9798162+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T02:42:27.9800596+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T02:42:37.5069265+05:30 80000038-0003-f200-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T02:42:40.4602892+05:30 80000038-0003-f200-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T02:43:37.6336009+05:30 80000026-0002-f800-b63f-84710c7967bb [ERR] The view '"SaveAssessment"' was not found. Searched locations: ["/Views/Assessment/SaveAssessment.cshtml", "/Views/Shared/SaveAssessment.cshtml"] (9bb2756c)
2020-08-05T02:43:37.7773148+05:30 80000026-0002-f800-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: The view 'SaveAssessment' was not found. The following locations were searched:
/Views/Assessment/SaveAssessment.cshtml
/Views/Shared/SaveAssessment.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2020-08-05T02:47:04.3289444+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T02:47:04.3650470+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T02:47:04.3652397+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T02:47:23.0796714+05:30 8000003e-0003-f200-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T02:47:25.9560530+05:30 8000003e-0003-f200-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Cannot return null from an action method with a return type of 'Microsoft.AspNetCore.Mvc.IActionResult'.
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.EnsureActionResultNotNull(ObjectMethodExecutor executor, IActionResult actionResult)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2020-08-05T02:47:47.4028285+05:30 80000051-0002-fb00-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T02:47:47.8828339+05:30 80000051-0002-fb00-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T02:51:57.4507652+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T02:51:57.4747274+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T02:51:57.4750132+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T02:52:08.1707577+05:30 80000075-0003-f600-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T02:52:11.4514880+05:30 80000075-0003-f600-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T02:57:41.9449622+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T02:57:42.0044760+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T02:57:42.0046366+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T02:57:52.6461360+05:30 80000042-0001-f900-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T02:57:55.8916909+05:30 80000042-0001-f900-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T03:00:31.3452728+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T03:00:31.3722776+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T03:00:31.3724024+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T03:00:40.9364206+05:30 80000073-0002-f700-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T03:00:44.2805760+05:30 80000073-0002-f700-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T03:05:20.8243841+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T03:05:20.8502133+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T03:05:20.8510465+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T03:05:31.6356234+05:30 8000005e-0001-f500-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T03:05:34.7042876+05:30 8000005e-0001-f500-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T03:07:48.4905896+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T03:07:48.5164812+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T03:07:48.5168531+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T03:07:59.0842179+05:30 80000062-0001-fa00-b63f-84710c7967bb [INF] ValidateUser UserName : "sENTHIL" (2a1eb942)
2020-08-05T03:08:01.8812025+05:30 80000062-0001-fa00-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Cannot return null from an action method with a return type of 'Microsoft.AspNetCore.Mvc.IActionResult'.
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.EnsureActionResultNotNull(ObjectMethodExecutor executor, IActionResult actionResult)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2020-08-05T03:08:11.2014974+05:30 80000064-0001-fa00-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T03:08:11.6447002+05:30 80000064-0001-fa00-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T03:08:56.9249716+05:30 80000082-0002-f700-b63f-84710c7967bb [ERR] The view '"SaveAssessment"' was not found. Searched locations: ["/Views/Assessment/SaveAssessment.cshtml", "/Views/Shared/SaveAssessment.cshtml"] (9bb2756c)
2020-08-05T03:08:56.9390375+05:30 80000082-0002-f700-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: The view 'SaveAssessment' was not found. The following locations were searched:
/Views/Assessment/SaveAssessment.cshtml
/Views/Shared/SaveAssessment.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2020-08-05T03:32:32.6763168+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T03:32:32.7006331+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T03:32:32.7008049+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T03:32:44.2134034+05:30 8000000b-0002-f400-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T03:32:47.3091706+05:30 8000000b-0002-f400-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T03:33:58.6598059+05:30 80000056-0001-f900-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at MemberOutReachSystem.Controllers.AssessmentController.GetMemberAssessment(String mbrid) in D:\data\C_drive\source\repos\MemberOutReachSystem\Controllers\AssessmentController.cs:line 129
   at MemberOutReachSystem.Controllers.AssessmentController.SaveAssessment() in D:\data\C_drive\source\repos\MemberOutReachSystem\Controllers\AssessmentController.cs:line 79
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2020-08-05T03:35:30.0173942+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T03:35:30.0422524+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T03:35:30.0423771+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T03:35:45.1793764+05:30 80000064-0002-fb00-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T03:35:48.1429133+05:30 80000064-0002-fb00-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T03:39:53.3038067+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T03:39:53.4025621+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T03:39:53.4029773+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T03:40:02.0758064+05:30 80000085-0003-f600-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T03:40:05.0043323+05:30 80000085-0003-f600-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T03:42:51.3059129+05:30 8000001b-0000-f400-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at AspNetCore.Views_AssessmentHistory_Index.ExecuteAsync() in D:\data\C_drive\source\repos\MemberOutReachSystem\Views\AssessmentHistory\Index.cshtml:line 25
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2020-08-05T03:47:17.5221308+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T03:47:17.5854707+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T03:47:17.5856322+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T03:49:39.0585904+05:30 80000076-0002-fb00-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T03:49:42.3671267+05:30 80000076-0002-fb00-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T03:52:48.0538632+05:30 80000058-0003-f200-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at AspNetCore.Views_AssessmentHistory_Index.ExecuteAsync() in D:\data\C_drive\source\repos\MemberOutReachSystem\Views\AssessmentHistory\Index.cshtml:line 25
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2020-08-05T03:53:39.8331947+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T03:53:39.8594881+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T03:53:39.8596925+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T03:53:58.0331761+05:30 8000007a-0001-fa00-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T03:54:01.1836421+05:30 8000007a-0001-fa00-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T03:54:51.8832784+05:30 8000004a-0003-f500-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at AspNetCore.Views_AssessmentHistory_Index.ExecuteAsync() in D:\data\C_drive\source\repos\MemberOutReachSystem\Views\AssessmentHistory\Index.cshtml:line 25
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2020-08-05T03:55:24.0510192+05:30 80000025-0002-f400-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at AspNetCore.Views_AssessmentHistory_Index.ExecuteAsync() in D:\data\C_drive\source\repos\MemberOutReachSystem\Views\AssessmentHistory\Index.cshtml:line 25
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2020-08-05T03:56:10.0109142+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T03:56:10.0580692+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T03:56:10.0584574+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T03:56:18.5853909+05:30 80000031-0000-f800-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T03:56:21.6528432+05:30 80000031-0000-f800-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T03:57:34.2705204+05:30 80000023-0001-f800-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at AspNetCore.Views_AssessmentHistory_Index.ExecuteAsync() in D:\data\C_drive\source\repos\MemberOutReachSystem\Views\AssessmentHistory\Index.cshtml:line 25
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2020-08-05T03:58:46.9295355+05:30 8000007c-0003-f800-b63f-84710c7967bb [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.NullReferenceException: Object reference not set to an instance of an object.
   at AspNetCore.Views_AssessmentHistory_Index.ExecuteAsync() in D:\data\C_drive\source\repos\MemberOutReachSystem\Views\AssessmentHistory\Index.cshtml:line 25
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2020-08-05T04:02:46.1355274+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T04:02:46.1590105+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T04:02:46.1593512+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T04:03:04.2448691+05:30 80000036-0001-fb00-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T04:03:07.2900131+05:30 80000036-0001-fb00-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T11:56:34.8728683+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T11:56:34.8966953+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T11:56:34.8968196+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T11:56:46.8700984+05:30 80000064-0003-f200-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T11:56:51.9153573+05:30 80000064-0003-f200-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T16:11:27.7097227+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T16:11:27.7497731+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T16:11:27.7499592+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T16:20:57.3944601+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T16:20:57.4204913+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T16:20:57.4207739+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T16:21:19.0979508+05:30 80000093-0000-fd00-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T16:21:23.0704821+05:30 80000093-0000-fd00-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T16:22:47.3556990+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T16:22:47.3866544+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T16:22:47.3871417+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T16:22:57.5943422+05:30 8000005f-0000-fc00-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T16:23:01.9495061+05:30 8000005f-0000-fc00-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T16:25:31.7188937+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T16:25:31.7501433+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T16:25:31.7502992+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T16:25:40.8357832+05:30 80000097-0002-f700-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T16:25:44.6199500+05:30 80000097-0002-f700-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T16:41:51.8618494+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T16:41:51.8916546+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T16:41:51.8921862+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T16:42:00.6641561+05:30 80000066-0001-f700-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T16:42:04.5740693+05:30 80000066-0001-f700-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T16:44:42.1765378+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T16:44:42.2230120+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T16:44:42.2231982+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T16:44:52.2366086+05:30 8000003a-0000-f700-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T16:44:55.8707171+05:30 8000003a-0000-f700-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T16:48:03.5185129+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T16:48:03.5470488+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T16:48:03.5471889+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T16:48:13.8266740+05:30 80000054-0003-f500-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T16:48:17.5318060+05:30 80000054-0003-f500-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T16:49:54.3057974+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T16:49:54.3333321+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T16:49:54.3335988+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T16:50:13.0360853+05:30 800000a7-0003-f600-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T16:50:16.4838680+05:30 800000a7-0003-f600-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T16:57:00.3399406+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T16:57:00.3724462+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T16:57:00.3726412+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T16:57:16.2095463+05:30 80000032-0000-f400-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T16:57:20.4493418+05:30 80000032-0000-f400-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T17:38:34.9343499+05:30 80000076-0001-f700-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T17:38:35.2125508+05:30 80000076-0001-f700-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T18:19:08.0511327+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T18:19:08.0795561+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T18:19:08.0797781+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
2020-08-05T18:19:49.2377587+05:30 8000004c-0000-f800-b63f-84710c7967bb [INF] ValidateUser UserName : "Senthil" (2a1eb942)
2020-08-05T18:19:54.2732377+05:30 8000004c-0000-f800-b63f-84710c7967bb [INF] Validate Succeed for UserName : "Senthil" (08d10229)
2020-08-05T18:42:44.2864880+05:30  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-05T18:42:44.3160973+05:30  [INF] Hosting environment: "Production" (c3307c92)
2020-08-05T18:42:44.3163836+05:30  [INF] Content root path: "D:\data\C_drive\source\repos\MemberOutReachSystem" (b5d60022)
